### ISSUE TITLE
How to verify cosign 3.0.* binaries from earlier versions of cosign?

### ISSUE THREAD

**Issue by ToBeReplaced** [sigstore/cosign#4459]
**Question**
I used to follow the steps here:
https://docs.sigstore.dev/cosign/system_config/installation/#verifying-cosign-binary

These steps no longer work with the `3.0.*` series, as `.pem` and `.sig` files are no longer distributed.

I see the new `.json` files, but I do not see a public key I can use in the `-kms` file, only a `hint`.

What steps can be used now? I have a previously verified cosign binary, but do not know how to verify one in the `3.0.*` chain without starting from scratch.

**Comment by Hayden-IO** [comment]
Hey, I’m working on a doc update now for this, stay tuned!

**Comment by Hayden-IO** [comment]
https://github.com/sigstore/docs/pull/396 has the updated instructions.

**Comment by ToBeReplaced** [comment]
Thank you for looking at this. Have the instructions been tested when verifying a `3.*` from `2.*`? I have:
```
curl --fail -Ss -O -L https://github.com/sigstore/cosign/releases/download/v3.0.2/cosign-linux-amd64
+ curl --fail -Ss -O -L https://github.com/sigstore/cosign/releases/download/v3.0.2/cosign-linux-amd64.sigstore.json
+ /bin/bootstrap-cosign verify-blob cosign-linux-amd64 --bundle cosign-linux-amd64.sigstore.json --certificate-identity keyless@projectsigstore.iam.gserviceaccount.com --certificate-oidc-issuer https://accounts.google.com
Error: bundle does not contain cert for verification, please provide public key
main.go:74: error during command execution: bundle does not contain cert for verification, please provide public key
```

... where `/bin/bootstrap-cosign` is version `2.2.1`.

**Comment by ToBeReplaced** [comment]
Ah, I have figured out the issue, the 2.x series must be at least `2.4.2`

```
$ curl -o cosign -sS -L https://github.com/sigstore/cosign/releases/download/v2.4.1/cosign-linux-amd64
$ chmod +x cosign
$ version=v3.0.2; os=linux-amd64
$ curl -s -o new-cosign -L https://github.com/sigstore/cosign/releases/download/$version/cosign-$os
$ curl -s -o cosign.sigstore.json -L https://github.com/sigstore/cosign/releases/download/$version/cosign-$os.sigstore.json
$ ./cosign verify-blob new-cosign --bundle cosign.sigstore.json   --certificate-identity keyless@projectsigstore.iam.gserviceaccount.com --certificate-oidc-issuer https://accounts.google.com
Error: bundle does not contain cert for verification, please provide public key
main.go:74: error during command execution: bundle does not contain cert for verification, please provide public key
```

```
$ curl -o cosign -sS -L https://github.com/sigstore/cosign/releases/download/v2.6.1/cosign-linux-amd64
$ ./cosign verify-blob new-cosign --bundle cosign.sigstore.json   --certificate-identity keyless@projectsigstore.iam.gserviceaccount.com --certificate-oidc-issuer https://accounts.google.com
Verified OK
```

Recommend updating the docs to indicate you must first have cosign `>=2.4.2`
