### ISSUE TITLE
API break in 3.10?

### ISSUE THREAD

**Issue by jas4711** [sigstore/cosign#4923]
Hi!  I tried to update cosign to 3.10 in Debian but building `gitsign` with it fails, but it worked with cosign 3.0.6.

https://salsa.debian.org/jas/cosign/-/jobs/9739742#L4793

```
# github.com/sigstore/gitsign/internal/commands/attest
src/github.com/sigstore/gitsign/internal/commands/attest/attest.go:78:36: undefined: signcommon.GetSignerVerifier
```

Seems like something changed in cosign triggering this problem?  Shouldn't cosign be bumped to v4 in this situation, signalling a API backwards compatibility break?

Thanks,
Simon

**Comment by sbirl** [comment]
Yeah, there's a `3.10` in [tags](https://github.com/sigstore/cosign/tags), but nothing to download under [releases](https://github.com/sigstore/cosign/releases), which is breaking my pipelines that depend on cosign.

**Comment by Hayden-IO** [comment]
Cosign unfortunately really wasn't designed to be an API, and we do specify that we offer no guarantees around API stability - https://github.com/sigstore/cosign/blob/main/VERSIONING.md#cosign-api. With a future Cosign version, we're planning to restructure the internals to surface a container signing API (blob signing should use sigstore-go) and hide the rest under internal/ to avoid issues like this, at which point we can guarantee stability and following semver.

> Yeah, there's a 3.10 in [tags](https://github.com/sigstore/cosign/tags), but nothing to download under [releases](https://github.com/sigstore/cosign/releases), which is breaking my pipelines that depend on cosign.

There was an issue with the release process, we're cutting a new release for 3.1.1 now.
